config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :images

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image_file, ImageUploader
  validates :image_file, :presence => true

  def encrypt
    logger.info "*****#{self.image_file}******"
    GPGME::Key.import(File.open(ENV.fetch 'KEY_FILE'))
    crypto = GPGME::Crypto.new(:password => ENV.fetch('KEY_FILE_PASSWORD'))
    self.image_file = crypto.encrypt(@image_file)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable
  devise :omniauthable, :omniauth_providers => [:google_oauth2]
  
  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    # Uncomment the section below if you want users to be created if they don't exist
    # unless user
    #     user = User.create(name: data["name"],
    #        email: data["email"],
    #        password: Devise.friendly_token[0,20]
    #     )
    # end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index

  end

  def new
    @image = Image.new
  end
  
  def create
    @image = Image.new(image_params)
    @image.encrypt
    logger.info "******#{@image.image_file}*****"
    if @image.save
      flash[:notice] = "Image successfully saved"
      redirect_to :action => :index
    else
      flash[:alert] = @image.errors.full_messages
      redirect_to :action => :new
    end
  end

  private
    def image_params
      params.fetch(:image, {}).permit(:image_file)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to images_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/images/index.html.erb
<h1>Images go here</h1>
<div class="row">
  <div class="col-lg-12">
    <%= link_to "Upload Image", new_image_path, :class => "btn btn-primary" %>
  </div>
</div>
<h2>Upload link here</h2>
<h3>Recent uploads here</h3>

app/views/images/new.html.erb
<h1>New Image</h1>
<%= simple_form_for(@image, :html => { :class => "form-horizontal" }) do |f| %>
  <%= f.input :image_file %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imagegard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <!-- header will go here --!>
    <div class="row">
      <div class="col-lg-10"></div>
      <div class="col-lg-2"><p class="text-right">
        <% if user_signed_in? %>
          <%= link_to 'Logout', destroy_user_session_path, :method => :delete, :class => 'btn btn-primary' %>
        <% else %>
          <%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2), :class => 'btn btn-primary' %><br />
        <% end %>
      </p></div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <% if notice %><p class="alert alert-info"><%= notice %></p><% end %>
        <% if alert %><p class="alert alert-danger"><%= alert %></p><% end %>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p class="bg-primary">Hello world</p>